### ISSUE TITLE
UploadImageComponent,   UploadFileComponent这两个组件files属性报错

### ISSUE THREAD

**Issue by bairui100** [godbasin/angular2-form-schame#2]
ERROR in [at-loader] ./node_modules/angular-form-components/src/upload-file/upload-file.component.ts:60:29 
    TS2339: Property 'files' does not exist on type 'HTMLElement'.

ERROR in [at-loader] ./node_modules/angular-form-components/src/upload-image/upload-image.component.ts:63:29 
    TS2339: Property 'files' does not exist on type 'HTMLElement'.

已经安装了jquery和bootstrap

**Comment by godbasin** [comment]
最新的master代码，并没有用到angular-form-components组件噢，请问是没更新最新master吗？
可以尝试下更新npm包或者项目代码，如果还有这种情况的话，麻烦提供下demo，谢谢~
